### ISSUE TITLE
Biome Updates not Displaying until Reload

### ISSUE THREAD

**Issue by bengalgod** [talonos2/BlightfallTracker#127]
I've been doing some "manual" cleansing using ethereal blooms, and I've had a lot of problem with small patches of taint seeming to persist indefinitely. Usually it winds up being two or three single blocks of "tainted land" that remain despite exposure to ethereal blooms, but upon reloading the game, they update to show properly cured locations. 
I've tried forcing block updates by placing and breaking things, but this hasn't seemed to help in most instances.

**Comment by talonos2** [comment]
That is a bug with Thaumcraft. The biome is correctly getting set on the
server, but is not propagating to the client. (Even when using single
player, Minecraft runs a mini-server that you then connect to locally. It's
_still_ a client server desync!)

Don't worry. The grass may be purple, but it will act like a healed biome
in all respects.

Anything that unloads the chunk (such as teleporting away and teleporting
back) will fix the issue. Also, Dawn totems and the dawn machine don't have
this bug. It is _only_ a problem with blooms from Thaumcraft because of the
way they handle their packets. This is another instance where if buggy mods
were open source, we would fix it.

**Comment by bengalgod** [comment]
Thanks for the quick response! Guess I'm climbing up the tech tree before I do anything on a large scale.
