### ISSUE TITLE
Metallurgy ingot aspects not applied correctly

### ISSUE THREAD

**Issue by omglolbah** [talonos2/BlightfallTracker#128]
EssentiaEverthing.zs lists Metallurgy ingots as having a variety of aspects.
None of these are applied. All ingots (as far as I can tell) are purely metallum.

Metallurgy ores have no aspects at all.

**Comment by SelenaQuartzRose** [comment]
Interesting. Several of them work as described in the EssentiaEverything.zs script. For example, Ceruclase Ingots have 3 Metallum and 1 Gelum as intended.

Some of them are broken, however. Vyroxeres is supposed to have 3 Metallum and 1 Venenum, but only has the Metallum. ("venenum" is misspelled as "veneum" in the script) 
Vulcanite, Shadow Steel, Zinc, and Brass should each contain 1 perditio, but do not because it is mis-spelled "perdito" in the script. 
Inolashite should contain vinculum, but the script mis-spells it as "viniculum". 

Sanguinite is also completely missed in the script and as a result the Sanguinite Ingot has no aspects. (@Talonos2: Might I suggest 3 Metallum, 1 Infernus, 1 Venenum? This is the metal that inflicts Wither.)

Hepatizon is missed as well and has no aspects. (Alloy of Bronze and Gold) (I would suggest 3 Metallum, 1 Instrumentum, and 1 Lucrum)

Mithril and Platinum are also missed. 
I would suggest: 
Mithril, (3 metallum, 1 volatus, 1 praecantatio)
Platinum, (3 metallum, 1 terra, 1 lucrum)

Everything else seems to work correctly as described in the script, from what I can tell.

I can confirm that metallurgy ores have no aspects to my knowledge. This actually irked me slightly in my Let's Play.

**Comment by talonos2** [comment]
That'd be why.

Spell-check fails on aspects.

I'll try fixing the script and hopefully that'll work.
