### ISSUE TITLE
Scout Missions Gone

### ISSUE THREAD

**Issue by TheForgotten1** [talonos2/BlightfallTracker#129]
I have recently completed all of the tech ore quests under the geologist tab, after this happened, all of my scouting missions were eradicated and replaced by ore cache missions. This disabled me from completing all of the alien ore quests, the colonist medal quests (including the big final one) And from getting more black market quests. Please either fix this, or, if this was intentionally done, tell me why. Thank you for taking time out of your day to read this. (and I also completed all the cache missions to see if that fixed it, which it did not)

**Comment by talonos2** [comment]
This is a known bug in HQM that happens when you join a team with a player
from another biodome. Did that happen, by any chance?

**Comment by TheForgotten1** [comment]
Yes it did, sadly.

**Comment by talonos2** [comment]
I am sorry. The simplest way to fix this is to delete players.dat from your
world save, and start the quest progression from scratch. The more
complicated way is to transfer players.dat into a single player world,
enable edit mode using the config option in /hqm/editmode.cfg, then, when
in the single-player world, use the command "/hqm edit" to get an op copy
of the book, and then use that to un-complete one of the two "Register for
team <Greek letter>" quests under the scout. Save it out, turn edit mode
back off in your configs, upload the players.dat to the sever. That
_should_ fix it.

The bug occurs when two "Register for team <x>" quests are complete at
once. This can _only_ happen if two people from different teams merge
parties, because those quests are configured so if one is completed, all
the others become invisible and un-completable. That's actually the bug; If
_two_ are completed somehow (such as through party merging), then _both_
become invisible and uncompletable. Because the scout quests require one of
the registration quests be completed, they _also_ become invisible and
uncompletable.

Sorry. :(
