### ISSUE TITLE
Quest book Crashing

### ISSUE THREAD

**Issue by Malenenshadow** [talonos2/BlightfallTracker#136]
Hay there! today me and the team started up another day in blightfall and for some reason our HQM book broke and causes us to crash whenever we open it! any idea why that would be happening?

**Comment by SelenaQuartzRose** [comment]
Please go to your technic launcher's directory and navigate to /modpacks/blightfall/crash-reports and open up the latest crash log there. (should be a .txt file named by the time and date of the crash)

Copy the entire contents of the crash report and paste them at www.pastebin.com, then submit the paste and post a link here. Alternatively, you could simply paste the contents of the crash log straight to github.

Without this, we can not find the source of your problem. Please submit this info ASAP.

**Comment by talonos2** [comment]
This often implies a mismatch between your quests and the quests on the server. It might be because you are running a different version of Blightfall than the server is, or perhaps that the server owner naively thought he could edit the quests server-side and it'd propagate client side.

Until I see logs, I'm going to close this as user error. Sorry. :(
