### ISSUE TITLE
Weapon rack causes irreversible repeated client crashes

### ISSUE THREAD

**Issue by UserAnon91** [talonos2/BlightfallTracker#139]
Paintbrushing a weapon rack causes an index out of range exception that force closes the client, rendering the chunk corrupted.  The issue we have is in a server i'm a staff on and need a solution to this without bringing down the entire server, as soon as possible.

http://pastebin.com/c248rdiL

**Comment by talonos2** [comment]
I'd open up the chunk in some external editing program such as NBTExplorer
or MCEdit and delete the affected block. That'll save the world at the cost
of whatever is in the weapon rack.

**Comment by Coolaxer** [comment]
Is there a possible fix though?

**Comment by talonos2** [comment]
The problem is obviously with CustomNPCs, and CustomNPCs is closed source.
CustomNPCs allows for modification and redistribution of its JAR file under
its license agreements, so we could try to make a fix, but it would involve
decompiling CustomNPCs and making a custom version. Given how few people
use paintbrushes, it might make sense to just disable the item, which I'll
look into next update. Which mod's paintbrush did you use? I know
openblocks isn't installed; is there a paint sprayer from Applied
Energistics?

**Comment by Coolaxer** [comment]
Quick question though, doesent that crash report seem like a curropt hqm file?

**Comment by CannibalVox** [comment]
Probably the server crashed for some other reason while HQM was writing and now the player quest data is corrupted.  Luckily, your lame-ass server doesn't really use that so you can just wipe it.

**Comment by talonos2** [comment]
Lol. It does look like an HQM crash.

I was replying to this from my E-mail, and for some reason, the E-mail
didn't provide the pastebin link.

http://i.imgur.com/8KWoud3.png?1

What a weird bug.

Yeah, I'll look into it, but any HQM issue is very unlikely to be fixed.

**Comment by Coolaxer** [comment]
Probably the server crashed for some other reason while HQM was writing and now the player quest data is corrupted. Luckily, your lame-ass server doesn't really use that so you can just wipe it.

Thats harsh. We stopped advertising on technic as you requested, shouldnt be talking like that to the server that has most of your players...

**Comment by talonos2** [comment]
Yeah, but it's not Coolaxe's server that's been hit. It's UserAnon91's.

But yeah, that could do it. Painting a weapon rack causes a crash, the crash happens to be while HQM is writing out data, data becomes corrupt, and that corruption causes a crash on world load.

If I recall, there's a backup of the player data in the world folder. You might try that.

**Comment by Coolaxer** [comment]
^

**Comment by talonos2** [comment]
Nah, they aren't our players, Coolaxe. In order to be "our players" they'd have to be playing "Blightfall", which we already told you they aren't. You keep doing your thing, we'll keep doing ours.

But seriously, please stop using our name.

**Comment by CannibalVox** [comment]
Also blightfall has half a million installs, you have a couple hundred dudes.

**Comment by Coolaxer** [comment]
All right all right. Fine, I wont argue on it anymore. Talonos gave me some stuff to work on, im doing it. Why you guys gotta be so mad?
Also blightfall has half a million installs, you have a couple hundred dudes.
I meant MP players

**Comment by talonos2** [comment]
Are you honestly asking why I am so mad? If so, I'll tell you. But I won't tell you if it's a rhetorical question.

Do you seriously want to know?

**Comment by Coolaxer** [comment]
Legit, if you could give me a proper answer.
Also, do you have some better methods of communication we can use.
But, seriously, we as a network appreciate what you do.

**Comment by Coolaxer** [comment]
The thing is, to my knowledge, there are only 2 established "Kitchen sink bfall"+Legit bfall servers
Us and MCConquer
Both of us have ditched the original map. The thing is, it is not made for Multiplayer minecraft, bfall was never intended to be anything other than a Friend/Lan/SP modpack. Why dont you guys notice that?

**Comment by talonos2** [comment]
I did Blightfall originally as a portfolio piece to try and score an internship doing game design work.

When recruiters try to determine whether or not to hire a person, they often look at the success of their past projects. In this case, I wouldn't be surprised if next time I submit a resume to a game company, they google "Blightfall" to see if I am really telling the truth about my accomplishments.

Currently, when you google Blightfall, "Blightfall-servers.com" is the fifth top result, and your server is the top result on that list. If somebody looking into Blightfall is tricked into thinking that Blightfall was designed for large servers (it wasn't) and that your half-implemented, pay-for-perks perversion of Blightfall is what I originally designed (it isn't) then they may come away thinking that I am not worth their consideration.

To a lesser degree, this is true of _any player_ that looks into Blightfall. If someone thinks Blightfall is just a modpack, like Attack of the B-Team or Hexxit or something, and they start by looking for a server instead of starting in a single-player world, they could legitimately be turned off by the whole thing. Blightfall was _never_ intended to be used by servers larger than about 30 people, and your attempts to shoehorn it into your pre-existing pay-for-perks paradigm is so far removed from the original design that it turns Blightfall into something else entirely.

Like, seriously, I don't mind you making a server that runs on the Blightfall modpack. I don't mind you monetizing it. But when you use the Blightfall name, you are telling the world that your server _is_ Blightfall (which it isn't) and _my_ reputation suffers. And indeed, that makes me mad, as much as I try to avoid it.

Just call it "Coolax's Taint World," mention that you connect by using the Blightfall modpack, and we'll all be fine. All I object to is your misrepresentation of our intellectual property.

I hope that answers your question as to why we are upset about this.

**Comment by Coolaxer** [comment]
Again, is there a place where we can talk about this in private? I would really like to talk about a few things.
"Pay-for-perks"
Please do elaborate.
"Currently, when you google Blightfall, "Blightfall-servers.com" is the fifth top result, and your server is the"
There is only 1 other active server there, which is also following our design. To be fair, all Kekisa (the server listing) requires you to have is a connectable experiance on the same modpack. I can rename the server on the server listing to Coolax Custom or something, but what I ask is - Will you really go after all of us (Chillax, Coolax, MCconquer) on this?

**Comment by unlucku** [comment]
Thank you for taking your time to look at this, and I completely understand your issue. The reason why I have this Blightfall server is because when it first came out, requests poured in from the players on our Attack of The B team server. They really wanted to challenge themselves to a Blightfall world, so I gave it to them. As others have said though, what I really have isn't Blightfall.

We are the number one top server on the Blightfall list, and I really want to keep it that way. Since the server's startup, we have been plagued by glitches, dupes, and angry players. Our top complaint is that our Blightfall server... Isn't really Blightfall. I have been working with my staff team and we have come up with a list of solutions to truly make our server Blightfall, and our goal is to keep players happy, and to inspire other servers to follow our method.

First of all, you're right when you say that Blightfall isn't really meant for a large server. I didn't know how big my server would initially get when I started it up. 

I plan on making a new world, one with a world border or around 40k. In this world will be a "safe radius" that will represent the safety domes that you are first teleported to on singleplayer. In this safe radius, players will be able to build and establish themselves, but they will never really progress in the game. In order for them to get good resources, they will be forced to venture out in to the rest of the world, which is tainted. 

Second, I know that there is a huge plot to Blightfall, and with our server... We kinda destroyed that idea. To counter this, I am going to disable the quest book (which is more affiliated with the smaller map) and create some NPCS with custom quests that resemble the book, and give very similar rewards. This way, the player can understand that there is a reason why they have to venture into the taint and purify the world, and also send samples back to the NPC's

I know you are angry, but I just want you to know that I am trying to do whatever I can do to make the server Blightfall, because I really just want everyone to be happy.

**Comment by UserAnon91** [comment]
I'm famous!

**Comment by talonos2** [comment]
Just so you know, I got both your previous reply (which you deleted) and this one as well. It makes me happy to see that you have cooled off and are looking for solutions instead of inflaming the situation. I really respect that.

Send me an E-mail when your server is ready. I'll hop on and take a look around. Best of luck. If you manage to recreate the Blightfall experience in a large, multi-player world, I will be _truly_ impressed and happy to mention it to those I know of. (So far, UnitedWorldMiners has been my "mega-server of choice," but I'm willing to re-evaluate.)

Also send me an E-mail of any dupe exploits you find. We caught and fixed the Motus Offering one, and we're interested in shutting down any others.

**Comment by unlucku** [comment]
We do have a bunch of dupe exploits, but unfortunately, I dont have your email...
Send it to coolaxgaming@gmail.com Then we can talk about that.
I have a huge list of potential dupes and exploits
