### ISSUE TITLE
Broke the supplier

### ISSUE THREAD

**Issue by Raclex** [talonos2/BlightfallTracker#194]
I don't know how I did it, but the supplier will not give me sapling, seed, or animal bags. I have 404 mission outlook and have waited DAYS for the cooldown period. Worked great until I started messing with parties. Not 100% sure, but I think the party stuff broke it somehow. Thoughts?

**Comment by talonos2** [comment]
Entirely possible. We've had issues with repeatable quests and parties
before. It has something to do with completing a quest when some people
have it on cooldown and others down. We've found and fixed one bug, but I
guess there's a second.

Use /hqm edit to "uncomplete" the quest. It should then complete
immediately (because of your high rep) and should thereafter work fine.

**Comment by Raclex** [comment]
That worked! Thank you for this awesome mod pack. It has been the most fun
Minecraft I've played since I first purchased Vanilla!
