### ISSUE TITLE
'Black Book' not given when taking seared bricks out of furnace.

### ISSUE THREAD

**Issue by Moleculor** [talonos2/BlightfallTracker#31]
Just removed 48 bricks baked from grout from a furnace. Don't remember precisely what key combination I used to remove them (right click? Left click? Shift right click? Shift left click? It was one of those, pretty sure), but when I removed them, I did not receive a book like the quest "Smeltery Bricks" says I should have received.

**Comment by talonos2** [comment]
So, i replaced the two volumes of "Materials and you" with Blightfall-specific versions, and turned off the "Spawn with beginner book" config option in TiC to keep there from being a confusing redundant version. Turns out, "Spawn with beginner book" also controls whether or not obtaining seared bricks gives you the smelting book; so they were disabled by accident.

I just changed the quest for the seared bricks quest to give you the black book instead, and updated the quest text to match.
