### ISSUE TITLE
Max speed of Archimedes Ships is too high

### ISSUE THREAD

**Issue by Vulpixy** [talonos2/BlightfallTracker#44]
It's currently set to 30 blocks a second max speed and I feel that's too fast considering the lag that would cause.

I would also recommend switching from a whitelist for allowed blocks to a blacklist to disable certain blocks. It will mean less work for you, and more freedom for building. I currently can't use the following blocks when building a ship:
Natura fence and fence gates
Natura crafting tables
Thaumcraft woods

Haven't checked any others yet.

**Comment by talonos2** [comment]
Two issues here:

First: You're completely right about the 30 blocks being too much. Next version is changed to 16, slightly faster than the fastest possible horse and more than twice as fast as a boat. That should be fast without being too fast.

Second, there are too many blocks in Blightfall to be able to blacklist all the problematic ones by hand. Just derping around for 30 minutes, I was able to identify 10 different blocks that all lost their contents upon being AS-ified. We've got to use a whilelist instead of a blacklist defensively, because there are too many ways things could go wrong, and trying to patch problems when they come up will lead to lots of unhappy people who get their stuff destroyed.

Most of the things you mention can work, and I'll add to the whitelist. Thaumcraft wood planks can't, because the thaumcraft woods share a blockID with the wooden thaumcraft machines. (Arcane bore, arcane bellows, etc) which can cause problems when moved. I'll add thaumcraft logs, though. (I should be able to copy the mrot settings from vanilla woods.)

**Comment by talonos2** [comment]
On second, thought, logs are a "Natural block" and should not be included lest you accidentally suck up a silverwood or something. Natura fences and crafting tables are now included in the whitelist. If you wish to give any more suggestions, I'm all ears. Just keep in mind anything with a rotation (like bibliocraft lamps, etc) is very hard to put in because one needs to decompile the source code of the mod in question to see how their rotation is represented by the block metadata. (But if you get working .mrot files for them, I'd put them in in a heartbeat!)
