### ISSUE TITLE
Impossible to get extra cotton seeds via farming

### ISSUE THREAD

**Issue by AKA-Syenite** [talonos2/BlightfallTracker#50]

**Comment by Dreamrisen** [comment]
I also noticed this. In other games, I have found that destroying the cotton plant when it has pink buds on it instead of the full white cotten drops multiple cotton seeds, but that did not seem to be the case. I didn't recognize it as a bug, so I didn't post it, but I do feel that there should be better ways of getting cotton than bonemealing grass and hoping to pick up some cotton seeds.

**Comment by talonos2** [comment]
This is a known issue with the interaction between Hunger Overhaul and Natura. I'm afraid it's out of our hands.

I can add a cotton -> cotton seeds recipe, though. That might help.
