### ISSUE TITLE
Thaumcraft's Outer Lands do not generate

### ISSUE THREAD

**Issue by HarbingTarbl** [talonos2/BlightfallTracker#64]
Entering the rift just leads to the character falling forever upon being transported to the outer lands dimension.

**Comment by talonos2** [comment]
Which rift did you open?

I was able to get the one on obelisk island to work.

**Comment by HarbingTarbl** [comment]
It was the one on obelisk island. I crafted the four eyes last night and activated the obelisk with a staff. I believe this world was created on  2.1.0 or  2.0.4c?  

Edit: Apparently the server owner didn't copy over all the world files when updating, would that have caused it?

**Comment by talonos2** [comment]
Worked just fine on my 2.1.1 version, in SSP. Last time I tested it was 2.0.4e, also in SSP. 

It might be possible it's an error that only appears on servers, kind of like the Last Millennium error was. Or yes, failing to copy over all the world folders may also have done it. Also, are you using Cauldron? Just curious.

![image](https://cloud.githubusercontent.com/assets/3359830/9419854/ae85da78-481c-11e5-9a6e-e52d14f14ad4.png)

If anybody else gets this issue, please let me know. Otherwise, I'll test it on a server next time I get a chance.

**Comment by HarbingTarbl** [comment]
Tried again on a fresh 2.1.1 world (SMP). Still not generating.

**Comment by talonos2** [comment]
We know what causes it, we're fixing it next patch, and you can fix
yourself it before next patch if you want.

There is a config option under server.properties called "Disable nether".
It's on, because you shouldn't have access to the Nether in Blightfall. It,
uh... actually disables all non-overworld dimensions.

Blame Notch.

Anyway, yeah. Flip "Disable nether" to false, and tell your players not to
go to the nether, and you'll be fine.
