### ISSUE TITLE
Fall from high place and die at spawn

### ISSUE THREAD

**Issue by NetMasterFlex** [talonos2/BlightfallTracker#89]
I recently downloaded and installed the blightfall server.  I installed the client from the technic launcher, join the server I'm hosted to only spawn in the sky and fall to my death.  I've tried deleting the world folder and have it re-create it, but the player continuously spawns in the air, falls to death, then gets banned.  Is there a world seed I'm supposed to be using? or is this a bug?

**Comment by talonos2** [comment]
You are supposed to spawn on a spaceship about 200 blocks above the surface
of a vast ocean. It seems like you spawn at the correct location, but your
server is not using the correct world file. Thus, you spawn 200 blocks
above randomly generated minecraft terrain, fall due to the lack of a
spaceship, and die.

Oh, and you shouldn't get banned, either. The provided world file has
hardcore mode disabled.

Are you hosting this server yourself, or using a third-party hosting
solution?

**Comment by NetMasterFlex** [comment]
I downloaded the file from http://technicpack.net/modpack/blightfall.592618 the file is: Blightfall_Server_v2.1.2.zip.  Once downloaded I extract the folder and move it's contents to a folder that I have reserved for it.  I start the server by clicking the launch bat file.  Once the serve is completely loaded I login from the client.

**Comment by NetMasterFlex** [comment]
Update.  I re-downloaded the server file, re-launched and I'm now spawning in the correct place.  This can be closed.  Thanks
