### ISSUE TITLE
Purple Slime Glitch

### ISSUE THREAD

**Issue by gregoryw3** [talonos2/BlightfallTracker#97]
If a large Purple slime is near the glass bearer it can spawn baby purple slime's through the glass.

**Comment by SelenaQuartzRose** [comment]
I believe that this is the intended functionality; if not, the bug is with Thaumcraft and there's not much the Blightfall team can do about it. In fact, if you kill the slime and read the quest "Tainted Slime Autopsy" available under the Xenobiologist, it notes: "the larger ones can 'shoot' smaller ones out of their mouths. This behavior has been observed to fire slimes through walls, so watch out."

I am not part of the Blightfall team, so I don't know for sure, but I believe that this is not something they intend to fix. It is an issue with Thaumcraft. Perhaps you could try reporting the bug to Azanor/The Thaumcraft team. But the changes will probably not make it into Blightfall because the next version of Thaumcraft is supposed to be the 1.8 version.

**Comment by talonos2** [comment]
The doctor is correct. There is a bug with Thaumcraft that we cannot fix
(but we would if we could!), so I hung a lampshade on it by specifically
warning people about it in the quest text. I'm sorry. :(
